### ISSUE TITLE
Form control - setValue - doesn't set value for new later added options

### ISSUE THREAD

**Issue by inzerceubytovani** [basvandenberg/angular2-select#10]
So after fix setValue after fix issue #5 it's not generate error when I try setValue in form with later added options. But it only add options, that were there initally - options which were added lately are not selected. Options, which were in select from the beginning display selected correctly, Hope you understand.

When I refresh page with F5, selected options are displayed correctly (including new ones)

**Comment by basvandenberg** [comment]
This situation seems to be working correctly for me after fixing issue #5 (and fix #6 improved the behavior). 

If you update the list of options, then the current selection is updated. All selected options that are not in the new list of options are removed, so that nothing can be selected that does not exist in the list of options. The selected options that are still in the updated list of options remain selected.

After updating the list of options, selecting the new options works fine for me.

How do you update the list of options? I replace the list of options with a new list. And now that I think of it, manipulating the current list of options (e.g. pushing new items to the list) will most probably not work (I think that this will not be detected by angular's change detection).

Could you maybe add some code to clarify your issue?

**Comment by inzerceubytovani** [comment]
I replace array of options this way: 
`this.touristAreasOptions = [];
touristAreas.forEach(region => this.touristAreasOptions.push({value: region._id, label: region.name}));`

I think that's allright. I tried also generate in forEach temporary array and then reassign to options, all goes same way.

So, this is what I do - I store values from select control with control.getValue to some persistant object. So when user return to page with this select , I use control.setValue to setup selected values to same as they were selected before.

Problem scenario: First I select same options (Selection 1) and save it to my variable with getValue (it's returns right values). Then I go back and with setValue select saved options - that's works great (of course they exists in selection options list so they can be selected). Now I do some action which generate new options list (with code showed above) - again no problem - works as you fixed in issue #5 and #6. Now I select new options (selection 2) - yes, I see them all right in selection list. But when I again use same process - setValues to my variable and then return back to page with form, I don't see options, which I newly selected in Selection 2 and which weren't between possible selection list in Selection 1. Options, which where between possible options in Selection 1 and were also selected in Selection 2 are correctly selected. But now when I refresh page (f5), also newly selected values in Selection 2 which weren't in Selection 1 options list are selected - this is expected result but  unfortunately after not until I refresh page with F5.

Hope this scenario descriptions is good enough. I checked in logs if all values are settings as they should be and there is everything all right.

Thank you for your support, really appreciate it.
