### ISSUE TITLE
Keep dropdown open when multiple

### ISSUE THREAD

**Issue by Adrian-AGM** [basvandenberg/angular2-select#100]
Is it possible to keep dropdown open when multiple property is true?
Could it be implemented?

**Comment by basvandenberg** [comment]
There were some tricky issues when taking this approach, which is why I know close it after selecting at option. This is also the same behavior as the select2 jquery plugin, and for now I would also like to stick to their behavior as much as possible for the 1.0 release.

I might have a look into this for later releases, but now it has low priority. Thanks for the input! I'll close the issue for now.
