### ISSUE TITLE
Cannot start application: "cannot find type definition for file for 'core-js'"

### ISSUE THREAD

**Issue by matthewhegarty** [basvandenberg/angular2-select#27]
Getting the current error on app start

```
node_modules/angular2-select/src/select-dropdown.component.d.ts(1,1): error TS2688: Cannot find type definition file for 'core-js'.
node_modules/angular2-select/src/select.component.d.ts(1,1): error TS2688: Cannot find type definition file for 'core-js'.
```

`tsconfig.json` refers to `"node_modules/@types/**/*.d.ts"`

I don't have the @types folder by default.  If I install with `npm install @types/core-js` then when I try to start application with `npm run start` I get loads of errors:

```
typings/globals/core-js/index.d.ts(3051,5): error TS2300: Duplicate identifier 'export='.
```

(removing `typings/globals/core-js` just gives different errors)

**Workaround:** If I remove the triple-slash directive at the top of the two *.d.ts files mentioned above then the issue goes away.  (others have fixed with a similar [hack](https://github.com/swimlane/angular2-data-table/commit/959b77dbfa1ea904fbe832ceafe5ff7cca85d8c9))

I have spent a few hours reading docs and I can't figure out how to do this properly.  Possibly upgrading to [Typescript 2.0 beta might fix it](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/), but haven't tried yet.

A full removal of `node_modules`, `typings` and then a `npm cache clean`, followed by a `npm install` doesn't fix the issue.

No idea what's going on here because the `angular2-select-demo` works ok on the same environment.
Any TypeScript experts able to help explain what's going on?

**Comment by basvandenberg** [comment]
Which version did you use, I made a mistake with the types in alpha.9 which should be fixed in alpha.10.

What does your tsconfig.json file look like? You might need to exclude some of the installed types to prevent the duplicate identifier error. However, I am also new to typescript and the type defenitions, so I am not sure if I can help you out.

Maybe I should make @types/core-js a peer dependency to make sure that it is installed by npm (I used npm for installing the types, and I hope everyone will start doing that, because having typescript as a second package manager is a bit double in my opinion). It could however be that some other package references the same type that is installed in the typings directory, so that it is installed twice at different locations (at least, that is what I think, I am not sure about this). I think that if `tsc` 'sees' both types it will throw the duplicate identifier error, so one of them should be excluded for typescript compilation.

But again, this is just a guess. I didn't have the time yet to dive into the typescript details...

**Comment by matthewhegarty** [comment]
- Currently using `alpha.12`.
- `tsconfig.json` matches that in `angular2-select-demo`
- typescript 2.0.3

I can now reproduce the issue in  [`angular2-select-demo`](https://github.com/matthewhegarty/angular2-select-demo/commit/e20f1c081b4ffa569b077f1f68ac6c58dd1128db)

Change `app.component.ts` line 89 to include the `SelectComponent` type
```
@ViewChild('singleSelectComponent') singleSelectComponent: SelectComponent;
```
and then import the type:

```
import {SelectComponent} from "angular2-select/src/select.component";
```
and run with `npm run build` - you should see the same two errors I'm getting.

This means I have a better workaround by removing the type from the declaration ie

```
@ViewChild('singleSelectComponent') singleSelectComponent;
```

works ok (`tsconfig.json: noImplicitAny` must be false)

I guess this issue should be fixed because we've lost type information. I've spent many hours trying to crack it with various approaches.  The error is clear enough - though it seems like it should work, because the reference to `core-js` is defined in `typings/index.d.ts`.  Will probably try a SO post.

**Comment by matthewhegarty** [comment]
I now have a more robust [fix](https://github.com/matthewhegarty/angular2-select-demo/commit/b385984f65553f06fc48591da34c78ccf80d30b5), which is "don't use typings".  It seems that an `npm install` is sufficient, and will work from a clean install.  This seems to be best practice, as described [here](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/)

**Comment by basvandenberg** [comment]
Thanks for looking into this. The easiest solution seems to be using angular-cli, which saves the trouble of defining a systemjs config (I think that angular-cli by now uses webpack instead of systemjs, but that is unrelated :). I will close the issue and will advice the use of angular-cli from now on. For another project I also didn't get building/testing to work with gulp/systemjs.
