### ISSUE TITLE
Multi select: show only the number of selected items in the header

### ISSUE THREAD

**Issue by farin99** [basvandenberg/angular2-select#29]
Is there an option to show only the number of selected items in the header and show check boxes inside the dropdown menu that will indicate what is selected.
Maybe instead of check box you can just put the selected options in bold.

**Comment by basvandenberg** [comment]
Sorry for the late response. 

There is no option to show the number of selected items in the header. I will consider this feature, but it will not have high priority.

I don't like having checkboxes in the dropdown. That would suggest you have to click the checkbox to select them, which is not the case.

The selected option(s) in the dropdown list are already marked (they have a grey background), so you can see which options are selected in the dropdown. You could use CSS to change this styling, for example if you want to use bold-face text instead of the grey background.

**Comment by basvandenberg** [comment]
Closing this issue for now, because showing the number of selected items in the header has low priority.
