### ISSUE TITLE
Can't clear selection

### ISSUE THREAD

**Issue by Oudstand** [basvandenberg/angular2-select#35]
If I try to clear the selection with the cross-button, the selection options will be displayed.

![unbenannt](https://cloud.githubusercontent.com/assets/15144268/20266456/71d89fb2-aa76-11e6-86a4-0130946b4354.PNG)

This is how I use the select:
in the html:
```

<form [formGroup]="form">
     <ng-select [options]="options" [allowClear]="true" 
         (selected)="setCategory($event)" (clear)="removeCategory()"                        
         formControlName="selectCategory" placeholder="Kategorie auswählen">
    </ng-select>
</form>
```

in the ts:
```
setOptions() {
        for (let category of this.categories) {
            this.options.push({
                value: category.id,
                label: category.name
            });
        }
    }

setDefaultSelectValue(category?: number) {
        this.form = new FormGroup({});
        this.form.addControl('selectCategory', new FormControl());

        if (category) {
            this.form.controls['selectCategory'].setValue(category);
        }

        this.displayCategory = true;
    }
```

I hope you can help me.

**Comment by basvandenberg** [comment]
The clear cross 'x' and the dropdown arrow seem to be overlapping each other. Probably the dropdown arrow is on top of the clear 'x', thereby preventing its click event to be triggered.

As you can see in this plunker (https://run.plnkr.co/2K3mgTlqMVPvFaa6/) the two should be next to each other. Did you somehow change the right padding of the span with class "select2-selection__rendered"? That padding 'pushes' the clear 'x' a little to the left, so that it does not overlap the arrow.

**Comment by Oudstand** [comment]
Thank you! I used a theme, that has overwritten the padding.
