### ISSUE TITLE
Issue with two way data binding not syncing

### ISSUE THREAD

**Issue by jacksoncharles** [basvandenberg/angular2-select#42]
I'm using your solution in a simple form with 2-way data binding. I have several select drop-downs each containing the same choices. When a user selects an option within SelectA I need to check and deselect the same option from the other drop-downs. To try and achieve this goal I hooked into the (selected) event and altered the properties that are bound to. Unfortunately the changes are not reflected in the DOM. My DOM elements are defined in a loop as follows:

    <ng-select name="{{ chosenAssets[asset.id] }}" id="{{ chosenAssets[asset.id] }}"
        [options]="options"
	placeholder="Select one"
	multiple="true"
	(selected)="selected($event, asset.id)"
	[(ngModel)]="chosenAssets[asset.id]"
	[ngModelOptions]="{standalone: true}"
    >
    </ng-select>

Any advice?

**Comment by basvandenberg** [comment]
Sorry, from this little piece of code I cannot tell if this is an issue in the select component or in your code, nor can I help in solving your issue. Either prepare a concrete example showing an issue in the select component, or expand the question (show more code) and ask a question on for example stackoverflow.

Instead of using the selected event, you can use [ngModelChange](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#ngModel) when using two-way data binding.

**Comment by matthewhegarty** [comment]
It's possible to dynamically change values of other drop-downs based on events from one.  I suggest not using ngModel and doing it imperatively.

1.  Maintain class level references to your drop-down options:

```
private dropdown1Options;
private dropdown2Options;
```
2.  Initialise these in `ngInit()`

3.  Setup a selected event: `(selected)="selected($event)"`

4. In your `selected()` function you can get the value of the event and then filter out from the options:

```
selected(item: any) {
    this.dropdown2Options = this.dropdown2Options.filter( each => {
        return each.id !== item.value
   }
}
```
