### ISSUE TITLE
can not able to change options once bind from model

### ISSUE THREAD

**Issue by AxarZalavadiya** [basvandenberg/angular2-select#60]
I have bind options using model that containing array of values, now If I change that model values from component then that change of values doesn't reflecting inside angular2-select.

**Comment by Azmalik51** [comment]
same issue

**Comment by basvandenberg** [comment]
This issue might have been solved in the beta release. On the [example page](https://basvandenberg.github.io/angular2-select/) there is the example "Update list of options" where the list of options can be changed by pressing a button. This use case works fine.

However, I think that your issue is caused by Angular's change detection. If one of the inputs changes, angular calls the [`onChanges`](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#onchanges) life cycle hook. It is mentioned that: 

> Angular only calls the hook when the value of the input property changes. The value of the hero property is the reference to the hero object. Angular doesn't care that the hero's own name property changed. The hero object reference didn't change so, from Angular's perspective, there is no change to report!

So the value of the options property is the reference to your options Array. This means that Angular will not detect changes in your options array, it will only detect if it is replaced with another array.

This means that, to change the options list, you would have to replace the bound options array with a new array with updated options. Maybe not so nice, but having to detect changes within arrays/objects is very expensive, so I guess that's why Angular only checks the object reference.
