### ISSUE TITLE
problem with making it required

### ISSUE THREAD

**Issue by BehnamAbdy** [basvandenberg/angular2-select#83]
hi guys

what should we do if we want to make this control to appear as required on form 
i tried adding the attribute of 'required' to it but did not

`<ng-select [options]="tenants" [(ngModel)]="model.matchTenantId" [ngModelOptions]="{standalone: true}" required>`

regards

**Comment by basvandenberg** [comment]
You can use angular's required validator ([`Validators.required`](https://angular.io/docs/ts/latest/api/forms/index/Validators-class.html)) in a reactive form.

See the third example in [this](https://basvandenberg.github.io/angular2-select/#value) section.

**Comment by neilhem** [comment]
In case of using not reactive forms we should have required option to pass to select component

**Comment by basvandenberg** [comment]
This component implement the [ControlValueAccessor](https://angular.io/docs/ts/latest/api/forms/index/ControlValueAccessor-interface.html) interface, so that it can be used as FormControl in a FormGroup. That's why you can use the required validator.

There is now way for this component to implement the required option 'by itself', because it is not aware of any form (parent) component.
